CREATE DATABASE mybbs;
use mybbs;
CREATE TABLE users (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(255),
    password VARCHAR(300) NOT NULL,
    level BOOL NOT NULL ,
    img VARCHAR(2550)

);

CREATE TABLE article (  
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,  
    user_id INT UNSIGNED NOT NULL,  
    title VARCHAR(255) NOT NULL,  
    body LONGTEXT NOT NULL,  
    level TINYINT NOT NULL,  
    time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,  
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE  
) ENGINE=InnoDB; 